name: "Terraform apply"

on:
  push:
    branches:
      - main
    paths:
      - "terragrunt/**"
      - ".github/workflows/**"
env:
  TERRAFORM_VERSION: 1.9.8
  TERRAGRUNT_VERSION: 0.68.2
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID}}
  ARM_TF_STATE_SUBSCRIPTION_ID: ${{ secrets.ARM_TF_STATE_SUBSCRIPTION_ID}}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  AZURE_RESOURCES_RESOURCE_GROUP_NAME: ${{ secrets.AZURE_RESOURCES_RESOURCE_GROUP_NAME}}
  AZURE_RESOURCES_STORAGE_ACCOUNT_NAME: ${{ secrets.AZURE_RESOURCES_STORAGE_ACCOUNT_NAME}}
  LOG_ANALYTICS_WORKSPACE_ID: ${{ secrets.LOG_ANALYTICS_WORKSPACE_ID }}
  SRE_EMAIL: ${{ secrets.SRE_EMAIL }}
  SECURITY_EMAIL: ${{ secrets.SECURITY_EMAIL }}

permissions:
  id-token: write
  contents: read

jobs:
  terragrunt-apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Terraform Tools
        uses: cds-snc/terraform-tools-setup@v1

        # Log into Azure
      - name: Azure Login using OIDC
        uses: azure/login@a457da9ea143d694b1b9c7c869ebb04ebe844ef5 # v2.3.0
        with:
          tenant-id: ${{ env.ARM_TENANT_ID }}
          client-id: ${{ env.ARM_CLIENT_ID }}
          subscription-id: ${{ env.ARM_TF_STATE_SUBSCRIPTION_ID}}

      - name: Apply Terraform 
        working-directory: terragrunt 
        env:
          ARM_USE_OIDC: true
        run: |
          terragrunt run-all init --terragrunt-non-interactive
          terragrunt apply --terragrunt-non-interactive -auto-approve